# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Users\Администратор\Desktop\Python\CODE\PB\pb_gui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(820, 400)
        font = QtGui.QFont()
        font.setPointSize(10)
        Form.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("PB images.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.btn_exit = QtWidgets.QPushButton(Form)
        self.btn_exit.setGeometry(QtCore.QRect(360, 370, 118, 24))
        self.btn_exit.setObjectName("btn_exit")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(270, 100, 311, 241))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_result_box = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_result_box.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_result_box.setObjectName("verticalLayout_result_box")
        self.horizontalLayout_result_data = QtWidgets.QHBoxLayout()
        self.horizontalLayout_result_data.setObjectName("horizontalLayout_result_data")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("border-color: rgb(0, 170, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_result_data.addWidget(self.label)
        self.label_date = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_date.setFont(font)
        self.label_date.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_date.setObjectName("label_date")
        self.horizontalLayout_result_data.addWidget(self.label_date)
        self.verticalLayout_result_box.addLayout(self.horizontalLayout_result_data)
        self.textEdit = QtWidgets.QTextEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit.setFont(font)
        self.textEdit.setAutoFormatting(QtWidgets.QTextEdit.AutoAll)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_result_box.addWidget(self.textEdit)
        self.horizontalLayout_btns = QtWidgets.QHBoxLayout()
        self.horizontalLayout_btns.setObjectName("horizontalLayout_btns")
        self.btn_request = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_request.setStyleSheet("\n"
"")
        self.btn_request.setObjectName("btn_request")
        self.horizontalLayout_btns.addWidget(self.btn_request)
        self.btn_copy = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_copy.setObjectName("btn_copy")
        self.horizontalLayout_btns.addWidget(self.btn_copy)
        self.btn_print = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_print.setObjectName("btn_print")
        self.horizontalLayout_btns.addWidget(self.btn_print)
        self.verticalLayout_result_box.addLayout(self.horizontalLayout_btns)
        self.layoutWidget1 = QtWidgets.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(130, 20, 591, 48))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.lcdNumber = QtWidgets.QLCDNumber(self.layoutWidget1)
        self.lcdNumber.setProperty("intValue", 0)
        self.lcdNumber.setObjectName("lcdNumber")
        self.horizontalLayout_4.addWidget(self.lcdNumber)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.label_period_start = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_period_start.setFont(font)
        self.label_period_start.setObjectName("label_period_start")
        self.horizontalLayout.addWidget(self.label_period_start)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.label_period_end = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_period_end.setFont(font)
        self.label_period_end.setObjectName("label_period_end")
        self.horizontalLayout_2.addWidget(self.label_period_end)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_3)
        self.layoutWidget2 = QtWidgets.QWidget(Form)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 100, 252, 239))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_calendar = QtWidgets.QLabel(self.layoutWidget2)
        self.label_calendar.setAlignment(QtCore.Qt.AlignCenter)
        self.label_calendar.setObjectName("label_calendar")
        self.verticalLayout_4.addWidget(self.label_calendar)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.layoutWidget2)
        self.calendarWidget.setSelectedDate(QtCore.QDate(2018, 11, 7))
        self.calendarWidget.setGridVisible(True)
        self.calendarWidget.setObjectName("calendarWidget")
        self.verticalLayout_3.addWidget(self.calendarWidget)
        self.btn_load_calendar = QtWidgets.QPushButton(self.layoutWidget2)
        self.btn_load_calendar.setObjectName("btn_load_calendar")
        self.verticalLayout_3.addWidget(self.btn_load_calendar)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.layoutWidget3 = QtWidgets.QWidget(Form)
        self.layoutWidget3.setGeometry(QtCore.QRect(590, 100, 211, 241))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.lcdNumber_sel_record = QtWidgets.QLCDNumber(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lcdNumber_sel_record.setFont(font)
        self.lcdNumber_sel_record.setStyleSheet("color: rgb(0, 0, 255);\n"
"")
        self.lcdNumber_sel_record.setSmallDecimalPoint(False)
        self.lcdNumber_sel_record.setDigitCount(3)
        self.lcdNumber_sel_record.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcdNumber_sel_record.setObjectName("lcdNumber_sel_record")
        self.verticalLayout_5.addWidget(self.lcdNumber_sel_record)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalSlider_sel_record = QtWidgets.QSlider(self.layoutWidget3)
        self.horizontalSlider_sel_record.setAutoFillBackground(False)
        self.horizontalSlider_sel_record.setMinimum(1)
        self.horizontalSlider_sel_record.setMaximum(15)
        self.horizontalSlider_sel_record.setProperty("value", 1)
        self.horizontalSlider_sel_record.setSliderPosition(1)
        self.horizontalSlider_sel_record.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_sel_record.setInvertedAppearance(False)
        self.horizontalSlider_sel_record.setObjectName("horizontalSlider_sel_record")
        self.verticalLayout_2.addWidget(self.horizontalSlider_sel_record)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btn_left = QtWidgets.QPushButton(self.layoutWidget3)
        self.btn_left.setObjectName("btn_left")
        self.horizontalLayout_6.addWidget(self.btn_left)
        self.btn_right = QtWidgets.QPushButton(self.layoutWidget3)
        self.btn_right.setObjectName("btn_right")
        self.horizontalLayout_6.addWidget(self.btn_right)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.btn_load = QtWidgets.QPushButton(self.layoutWidget3)
        self.btn_load.setObjectName("btn_load")
        self.verticalLayout_5.addWidget(self.btn_load)
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(20, 80, 801, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(10, 350, 811, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.btn_exit.raise_()
        self.line.raise_()
        self.line_2.raise_()
        self.label.setBuddy(self.textEdit)
        self.label_date.setBuddy(self.textEdit)
        self.label_calendar.setBuddy(self.calendarWidget)
        self.label_6.setBuddy(self.horizontalSlider_sel_record)

        self.retranslateUi(Form)
        self.btn_copy.clicked.connect(self.textEdit.copy)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Privat Bank API"))
        self.btn_exit.setText(_translate("Form", "Выход"))
        self.label.setText(_translate("Form", "Карта"))
        self.label_date.setText(_translate("Form", "Дата"))
        self.textEdit.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt;\"><br /></p></body></html>"))
        self.btn_request.setText(_translate("Form", "Новый запрос"))
        self.btn_copy.setText(_translate("Form", "Copy"))
        self.btn_print.setToolTip(_translate("Form", "<html><head/><body><p>Print Tool Tip</p></body></html>"))
        self.btn_print.setWhatsThis(_translate("Form", "<html><head/><body><p>Print command What this</p></body></html>"))
        self.btn_print.setText(_translate("Form", "Печать"))
        self.label_2.setText(_translate("Form", "Записей в БД"))
        self.label_3.setText(_translate("Form", "Период"))
        self.label_4.setText(_translate("Form", "с: "))
        self.label_period_start.setText(_translate("Form", "Начало"))
        self.label_5.setText(_translate("Form", "По: "))
        self.label_period_end.setText(_translate("Form", "Конец"))
        self.label_calendar.setText(_translate("Form", "Выбор записи"))
        self.btn_load_calendar.setText(_translate("Form", "Загрузить"))
        self.label_6.setText(_translate("Form", "Выбор записи"))
        self.btn_left.setText(_translate("Form", "<--"))
        self.btn_right.setText(_translate("Form", "-->"))
        self.btn_load.setText(_translate("Form", "Загрузить"))

