# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Users\Администратор\Desktop\Python\CODE\PB\pb_gui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(646, 580)
        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setEnabled(True)
        self.progressBar.setGeometry(QtCore.QRect(60, 480, 371, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(60, 194, 371, 281))
        self.widget.setObjectName("widget")
        self.verticalLayout_result_box = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_result_box.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_result_box.setObjectName("verticalLayout_result_box")
        self.horizontalLayout_result_data = QtWidgets.QHBoxLayout()
        self.horizontalLayout_result_data.setObjectName("horizontalLayout_result_data")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_result_data.addWidget(self.label)
        self.label_date = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_date.setFont(font)
        self.label_date.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_date.setObjectName("label_date")
        self.horizontalLayout_result_data.addWidget(self.label_date)
        self.verticalLayout_result_box.addLayout(self.horizontalLayout_result_data)
        self.textEdit = QtWidgets.QTextEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit.setFont(font)
        self.textEdit.setAutoFormatting(QtWidgets.QTextEdit.AutoAll)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_result_box.addWidget(self.textEdit)
        self.horizontalLayout_btns = QtWidgets.QHBoxLayout()
        self.horizontalLayout_btns.setObjectName("horizontalLayout_btns")
        self.btn_request = QtWidgets.QPushButton(self.widget)
        self.btn_request.setObjectName("btn_request")
        self.horizontalLayout_btns.addWidget(self.btn_request)
        self.btn_print = QtWidgets.QPushButton(self.widget)
        self.btn_print.setObjectName("btn_print")
        self.horizontalLayout_btns.addWidget(self.btn_print)
        self.btn_exit = QtWidgets.QPushButton(self.widget)
        self.btn_exit.setObjectName("btn_exit")
        self.horizontalLayout_btns.addWidget(self.btn_exit)
        self.verticalLayout_result_box.addLayout(self.horizontalLayout_btns)
        self.widget1 = QtWidgets.QWidget(Form)
        self.widget1.setGeometry(QtCore.QRect(20, 13, 471, 48))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.lcdNumber = QtWidgets.QLCDNumber(self.widget1)
        self.lcdNumber.setProperty("intValue", 0)
        self.lcdNumber.setObjectName("lcdNumber")
        self.horizontalLayout_4.addWidget(self.lcdNumber)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.widget1)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.label_period_start = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_period_start.setFont(font)
        self.label_period_start.setObjectName("label_period_start")
        self.horizontalLayout.addWidget(self.label_period_start)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.widget1)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.label_period_end = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_period_end.setFont(font)
        self.label_period_end.setObjectName("label_period_end")
        self.horizontalLayout_2.addWidget(self.label_period_end)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_3)
        self.widget2 = QtWidgets.QWidget(Form)
        self.widget2.setGeometry(QtCore.QRect(20, 83, 471, 51))
        self.widget2.setObjectName("widget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalSlider_sel_record = QtWidgets.QSlider(self.widget2)
        self.horizontalSlider_sel_record.setAutoFillBackground(False)
        self.horizontalSlider_sel_record.setMinimum(1)
        self.horizontalSlider_sel_record.setMaximum(15)
        self.horizontalSlider_sel_record.setProperty("value", 1)
        self.horizontalSlider_sel_record.setSliderPosition(1)
        self.horizontalSlider_sel_record.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_sel_record.setInvertedAppearance(False)
        self.horizontalSlider_sel_record.setObjectName("horizontalSlider_sel_record")
        self.horizontalLayout_6.addWidget(self.horizontalSlider_sel_record)
        self.lcdNumber_sel_record = QtWidgets.QLCDNumber(self.widget2)
        self.lcdNumber_sel_record.setObjectName("lcdNumber_sel_record")
        self.horizontalLayout_6.addWidget(self.lcdNumber_sel_record)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_6)
        self.btn_load = QtWidgets.QPushButton(self.widget2)
        self.btn_load.setObjectName("btn_load")
        self.horizontalLayout_7.addWidget(self.btn_load)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.label_period_start.raise_()
        self.label_period_end.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_date.raise_()
        self.progressBar.raise_()
        self.horizontalSlider_sel_record.raise_()
        self.lcdNumber_sel_record.raise_()
        self.btn_load.raise_()
        self.label_6.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Карта"))
        self.label_date.setText(_translate("Form", "Дата"))
        self.textEdit.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt;\"><br /></p></body></html>"))
        self.btn_request.setText(_translate("Form", "Запрос PB API"))
        self.btn_print.setText(_translate("Form", "Печать"))
        self.btn_exit.setText(_translate("Form", "Выход"))
        self.label_2.setText(_translate("Form", "Записей в БД"))
        self.label_3.setText(_translate("Form", "Период"))
        self.label_4.setText(_translate("Form", "с: "))
        self.label_period_start.setText(_translate("Form", "Начало"))
        self.label_5.setText(_translate("Form", "По: "))
        self.label_period_end.setText(_translate("Form", "Конец"))
        self.label_6.setText(_translate("Form", "Выбор записи"))
        self.btn_load.setText(_translate("Form", "Загрузить"))

